[package]
name = "delegate-trait-proc-macros"
version = "0.0.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.68", features = ["full"] }
quote = "1.0.36"
proc-macro2 = { version = "1.0.86" }
